export const sentenceBank = [
"The quiet park filled with laughter as children played tag until sunset.",
  "After work, he stopped for coffee and sat watching the rain through glass.",
  "She read the letter twice, unsure whether to laugh, cry, or simply smile.",
  "A small cat leapt gracefully across the sofa, chasing a ray of sunlight.",
  "The library felt alive, full of whispers, footsteps, and the turning of pages.",
  "Under a crimson sky, the fishermen packed their nets and headed back home.",
  "They planned the trip carefully, noting each stop, hotel, and scenic trail.",
  "Her painting, once hidden in the attic, finally found a place on the wall.",
  "By morning, the storm had passed, leaving puddles and fresh air everywhere.",
  "The sound of waves crashing against the shore calmed his restless thoughts.",
  "We gathered for dinner, sharing stories, laughter, and bowls of warm soup.",
  "In spring, the garden bursts with tulips, daisies, and buzzing honeybees.",
  "He tied his shoes tightly, preparing to run along the old dirt country road.",
  "The clock struck midnight, yet the party continued with music and laughter.",
  "She typed the final sentence, relieved her report was finished on schedule.",
  "A dog barked in the distance as the mail carrier approached with packages.",
  "Their voices echoed through the hall as the debate grew heated and sharp.",
  "The mountain trail was steep, but the view from the summit was worth it.",
  "He folded the letter neatly and placed it inside the old wooden drawer.",
  "The smell of baked bread filled the kitchen, warm and inviting to all.",
  "They sang by the fire, their faces glowing in the flickering candlelight.",
  "The streets were quiet at dawn, with only the baker and milkman at work.",
  "I carried the lantern carefully, its dim glow lighting each uncertain step.",
  "Her shoes clicked on the pavement as she hurried to catch the morning bus.",
  "Snow blanketed the rooftops, softening the city’s edges into gentle curves.",
  "The train rumbled past, shaking the ground beneath our feet as we waited.",
  "He set the table with care, polishing each fork, knife, and shining glass.",
  "Morning sunlight streamed through the curtains, brightening the silent room.",
  "The wind rustled the trees, scattering golden leaves across the driveway.",
  "She hummed a quiet tune while chopping carrots and stirring a pot of soup.",
  "The candle flickered in the draft, casting strange shadows along the wall.",
  "Children chased bubbles, their laughter drifting across the summer lawn.",
  "The teacher wrote clearly on the board, her chalk squeaking with each word.",
  "I poured hot tea, watching steam rise slowly into the cool autumn air.",
  "The farmer loaded hay bales onto the wagon under the fading evening light.",
  "He glanced at the map again, tracing the route with his worn index finger.",
  "They clapped and cheered as fireworks painted the sky in dazzling colors.",
  "The cat purred softly, curling itself tighter on the old knitted blanket.",
  "She zipped her coat, braced against the chill, and stepped into the snow.",
  "Birds chirped merrily at sunrise, filling the air with cheerful melodies.",
  "The bookstore smelled of ink, paper, and the faint aroma of old leather.",
  "I scribbled notes quickly, hoping not to miss any of the professor’s words.",
  "The river flowed calmly, reflecting clouds drifting lazily across the sky.",
  "Under the porch, a family of kittens huddled together for warmth and sleep.",
  "She packed her suitcase with clothes, books, and a small stuffed animal.",
  "We walked through the museum slowly, admiring paintings that told stories.",
  "The baker dusted flour off his hands and placed fresh bread on display.",
  "A candlelit dinner on the balcony gave the evening a touch of romance.",
  "The thunder roared loudly, rattling windows and startling the sleepy dog.",
  "His journal, filled with sketches, captured moments of travel and silence.",
  "She placed the bouquet in water, arranging each flower with gentle care.",
  "They skated on the frozen pond, laughter echoing across the icy surface.",
  "The violinist bowed gracefully, filling the hall with sweet, haunting notes.",
  "Leaves crunched underfoot as we wandered down the quiet forest pathway.",
  "The bakery sign swung gently in the breeze, creaking against rusty chains.",
  "He polished the old watch, its ticking sound steady and reassuring still.",
  "We sat by the campfire, roasting marshmallows beneath a sky full of stars.",
  "The lighthouse beam cut across the waves, guiding ships through the night.",
  "She turned the last page of her book, sighing at the bittersweet ending.",
  "The market bustled with noise, colors, and smells of fruits and spices.",
  "I traced circles in the sand while waves lapped gently against the shore.",
  "The attic was dusty, filled with boxes of photographs and forgotten toys.",
  "The dog wagged his tail, waiting eagerly for a treat from his young owner.",
  "The bakery shelves emptied quickly as customers filled baskets with bread.",
  "She painted with bold strokes, bright colors dancing across the canvas.",
  "The letterbox rattled as the postman delivered another stack of envelopes.",
  "A cool breeze carried the scent of pine and the sound of distant bells.",
  "We planted seeds together, hoping the garden would bloom in the spring.",
  "The kettle whistled sharply, announcing tea was ready on the stovetop.",
  "Her laughter echoed, filling the café with warmth on a cold afternoon.",
  "Snowflakes landed softly on his glove, melting before he brushed them off.",
  "He admired the skyline, lights twinkling like stars across the horizon.",
  "The bicycle leaned against the fence, its wheels muddy from the trail.",
  "They set up the tent before sunset, eager to rest after the long hike.",
  "The city streets glowed with lanterns during the lively evening festival.",
  "I tapped the pencil nervously, waiting for the exam paper to be handed out.",
  "The fisherman cast his net, watching ripples spread across the wide lake.",
  "She poured orange juice, humming quietly while breakfast sizzled nearby.",
  "We strolled by the river, throwing breadcrumbs to ducks swimming lazily.",
  "The chalk drawings faded slowly after rain washed across the playground.",
  "The little boy clutched his toy car, refusing to let go even at bedtime.",
  "Her scarf blew in the wind as she crossed the busy city intersection.",
  "A sparrow perched on the window sill, chirping brightly into the room.",
  "The alarm rang, pulling me reluctantly out of a deep, pleasant dream.",
  "We carved pumpkins on the porch, laughing as candlelight flickered inside.",
  "She polished her shoes until they gleamed, proud of their spotless shine.",
  "The night air smelled of rain, earth, and the faint scent of jasmine.",
  "I dropped coins into the fountain, wishing quietly for peace and health.",
  "The board creaked underfoot as we tiptoed across the old wooden bridge.",
  "He folded the blanket neatly and placed it carefully back on the chair.",
  "The garden fountain gurgled cheerfully, attracting butterflies and bees.",
  "A gust of wind scattered papers across the desk and onto the floor.",
  "We leaned against the fence, watching horses graze quietly in the field.",
  "Her handwriting curled neatly across the page, graceful and deliberate.",
  "The waves foamed against the rocks, spraying mist into the salty air.",
  "A row of candles flickered in the chapel, glowing softly in silence.",
  "The phone buzzed with a message that instantly brightened her gloomy day.",
  "Children drew pictures with chalk, filling the sidewalk with bright art.",
  "The clock chimed six times, announcing the end of another busy school day.",
  "I zipped up my jacket tightly, bracing against the sharp winter wind.",   
  "She placed the lantern on the table, its glow softening the dark corners.",
  "The forest echoed with birdsong while sunlight filtered through tall trees.",
  "A gentle breeze carried scents of lilac and pine across the empty meadow.",
  "We waited on the platform, listening to the whistle of the incoming train.",
  "The puppy chased its tail, tumbling clumsily across the wooden kitchen floor.",
  "She folded the scarf, remembering the winter it had kept her warm and safe.",
  "The painter dabbed bright colors, each stroke adding life to the blank canvas.",
  "Leaves rustled in the courtyard as footsteps echoed between the stone walls.",
  "The fireplace crackled warmly, filling the cabin with light and gentle heat.",
  "I tied my shoelaces tightly before jogging down the foggy, quiet morning road.",
  "The waves rolled steadily, crashing with rhythm that soothed the weary sailor.",
  "Children built a sandcastle, their laughter mixing with the calls of gulls.",
  "The smell of roasted coffee beans drifted across the busy morning market.",
  "She scribbled notes in the margin, ideas flowing faster than she could write.",
  "The guitar’s gentle strumming filled the café with warmth on a rainy night.",
  "Snow gathered on the window ledge, sparkling faintly in the morning light.",
  "A cricket chirped loudly outside, breaking the silence of the warm summer air.",
  "The chef chopped vegetables quickly, steam rising from the simmering pan.",
  "A candle’s flame danced, shadows shifting along the old cracked stone wall.",
  "The soldier polished his boots, his thoughts wandering to home and family.",
  "I stacked books carefully, each cover worn from years of endless reading.",
  "The meadow glowed golden as the sun dipped beneath the distant mountain line.",
  "She brushed dust off the shelf, revealing forgotten trinkets and old photos.",
  "The lantern swayed gently, casting a faint glow along the cobblestone path.",
  "Children’s drawings hung proudly on the fridge, colorful and filled with joy.",
  "The horse trotted steadily, its hooves thudding against the dirt country road.",
  "We brewed tea by the fire, listening to raindrops patter against the roof.",
  "A sparrow fluttered away as the door creaked open in the still, cold night.",
  "The curtain fluttered as wind blew through the open window into the room.",
  "He wound the old clock, its ticking echoing softly through the silent hall.",
  "The letter smelled faintly of lavender, though the words inside were heavy.",
  "The cat knocked over a glass, startling itself as water spilled everywhere.",
  "Her sandals clicked lightly on the marble, echoing in the grand empty hall.",
  "I sharpened the pencil, ready to sketch the outline of the quiet landscape.",
  "The town square bustled with chatter, merchants selling spices and fabrics.",
  "She stirred sugar into her tea, staring out the window at the drifting snow.",
  "The violin’s notes rose slowly, filling the theater with tender emotion.",
  "The bakery’s glass fogged as fresh loaves filled the air with warmth inside.",
  "He lifted the crate onto the shelf, wiping sweat from his tired forehead.",
  "The tide came in slowly, swallowing footprints left across the sandy shore.",
  "We carried baskets of apples, their red skins shining in the autumn sun.",
  "A gust blew the hat from his head, rolling it across the grassy hillside.",
  "The teacher stacked papers neatly, sighing after another long busy day.",
  "Her earrings glittered under the lights, catching everyone’s attention.",
  "The library clock ticked faintly, unnoticed by the students deep in study.",
  "He traced the outline of the mountain with his finger across the old map.",
  "The night train rattled along, its whistle piercing the quiet countryside.",
  "A cat stretched lazily on the porch, blinking at the slow setting sun.",
  "The orchard smelled of ripe fruit, buzzing bees darting between blossoms.",
  "I buttoned my coat, bracing myself for the icy winds outside the station.",
  "The pilot checked his instruments carefully before taking off at sunrise.",
  "A lantern lit the dockside, fishermen hauling nets with tired heavy arms.",
  "The perfume lingered faintly, reminding him of the evening long since past.",
  "We laughed at the rain, running through puddles and splashing each other.",
  "The garden was alive with butterflies, wings flashing blue, gold, and red.",
  "The baker’s apron was dusted white as he placed bread to cool on the rack.",
  "A bicycle bell rang faintly as children raced down the narrow alleyway.",
  "The festival lights reflected in the river, shimmering like broken stars.",
  "She closed the diary gently, locking away secrets she could never share.",
  "The fox darted quickly through the underbrush, tail flashing in the dark.",
  "A kettle whistled sharply, steam rising as the kitchen filled with aroma.",
  "The sky burned orange at dusk, shadows stretching across the empty road.",
  "The fisherman hauled his catch, the boat rocking gently with each wave.",
  "I stacked firewood by the cabin, smoke already curling from the chimney.",
  "She tied the ribbon around the letter, smiling faintly at the memory.",
  "The bells rang loudly at noon, echoing across the rooftops of the town.",
  "We followed the path deeper into the forest, moss soft beneath our feet.",
  "The train conductor called out, signaling passengers to board quickly.",
  "Her painting of sunflowers glowed, vibrant against the gallery’s white wall.",
  "A lantern swung above the barn door, creaking in the chilly night wind.",
  "The old record played softly, filling the room with nostalgic melody.",
  "He carried water buckets, arms straining under the heavy wooden yoke.",
  "The tavern roared with laughter as music spilled from fiddles and drums.",
  "She painted stars on the ceiling, glowing faintly when the lights went out.",
  "We shared stories by the river, tossing stones that rippled the water.",
  "The bakery bell jingled as another customer entered with a hungry smile.",
  "The clouds parted slowly, moonlight spilling across the empty meadow.",
  "A match flared brightly, then dimmed as the candle began to flicker.",
  "The distant howl of a wolf echoed eerily across the silent valley.",
  "The boat rocked gently, ropes creaking as waves slapped against the hull.",
  "He carved his initials into the tree, smiling at the memory it held.",
  "The stars blinked above, countless lights scattered across the night sky.",
  "She poured warm soup into bowls, steam rising in the chilly farmhouse.",
  "The attic smelled of cedar, boxes stacked with letters tied in twine.",
  "We sat in silence, listening to the rain tap against the tin rooftop.",
  "The bonfire crackled, sparks leaping upward into the dark evening sky.",
  "Children’s voices rang out, playing hide and seek across the courtyard.",
  "The cobblestones glistened after rain, lanterns casting golden pools.",
  "He leaned back in the chair, sipping tea and enjoying the quiet moment.",
  "The lantern’s glow lit the staircase, revealing dust swirling in air.",
  "We strung lanterns between trees, the garden glowing with golden light.",
  "The orchard path twisted, lined with fallen apples and buzzing insects.",
  "She polished the silver spoons, watching them gleam in the dim sunlight.",
  "The town bells chimed together, calling everyone to the village square.",
  "The stream babbled gently, frogs croaking in rhythm as crickets chirped.",
  "He stretched his arms, relieved after hours bent over his desk of papers.",
  "The market’s scents mixed—fresh bread, spices, and flowers wrapped tight.",
  "We wrapped blankets tightly around ourselves, the fire keeping us warm.",
  "The morning fog lifted slowly, revealing rooftops shining in the dew."
];
